

GET https://cse341-scheduler.herokuapp.com/api/get-available

###

GET https://cse341-scheduler.herokuapp.com/api/get-available?doctor=Stevenson


###

POST https://cse341-scheduler.herokuapp.com/api/set-appointment-request
content-type: application/json

{
    "start": "2022-03-18T05:28:31.019+00:00",
    "end": "2022-03-18T05:28:31.019+00:00",
    "patient": "Joe",
    "doctor": "Stevenson"
}

###

